## default config
server:
  port: 8892
  session:
    timeout: 1800
  context-path: /
  undertow:
    accesslog:
      enabled: true
      dir: /data/log/okr/okr-web-log/
      prefix: okr-web-access.
  error:
      path: /error
spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/data/file/

logging:
  level:
    root: debug
  file: /data/log/okr/okr-web-log/okr-web

---
server:
  undertow:
    accesslog:
      dir: ../log
      prefix: ../log/okr-web-access.
  session:
    timeout: 10800

spring:
  profiles: local
logging:
  file: ../log/okr-web

---
spring:
  profiles: dev

app:
  jsDebug: true

---
spring:
  profiles: test

---
spring:
  profiles: uat

---
spring:
  profiles: prd

app:
  jsDebug: true
